apiVersion: pipeline.knative.dev/v1alpha1
kind: Task
metadata:
  name: build-docker-image-from-git-source
spec:
  inputs:
    resources:
      - name: source
        type: git
    params:
      - name: pathToDockerFile
        description: The path to the dockerfile to build
        default: /workspace/source/Dockerfile
      - name: baseWorkspace
        description: The path to the base source workspace
        default: /workspace/source
      - name: pathToContext
        description:
          The build context used by Kaniko
          (https://github.com/GoogleContainerTools/kaniko#kaniko-build-contexts)
        default:  /workspace/source
  outputs:
    resources:
      - name: dlang-image
        type: image
      - name: go-image
        type: image
      - name: go-maven-image
        type: image
      - name: gradle-image
        type: image
      - name: maven-image
        type: image
      - name: nodejs-image
        type: image
  steps:
    - name: warm-cache
      image: gcr.io/kaniko-project/warmer
      args:
        - --cache-dir=/workspace
        - --image=docker.io/jenkinsxio/builder-base:0.1.230
      resources:
        limits:
          cpu: 2
          memory: 4096Mi
        requests:
          cpu: 1
          memory: 2018Mi
    - name: build-and-push-gradle
      image: rawlingsj/executor:dev16
      command:
        - /kaniko/executor
      args:
        - --dockerfile=${inputs.params.baseWorkspace}/builder-gradle/Dockerfile
        - --destination=${outputs.resources.gradle-image.url}
        - --context=${inputs.params.baseWorkspace}/builder-gradle
        - --cache-repo=jenkins-x-docker-registry:5000/
        - --cache=true
        - --cache-dir=/workspace
        - --skip-tls-verify-registry=jenkins-x-docker-registry:5000
      resources:
        limits:
          cpu: 4
          memory: 8192Mi
        requests:
          cpu: 2
          memory: 4096Mi
    - name: build-and-push-dlang
      image: rawlingsj/executor:dev16
      command:
        - /kaniko/executor
      args:
        - --dockerfile=${inputs.params.baseWorkspace}/builder-dlang/Dockerfile
        - --destination=${outputs.resources.dlang-image.url}
        - --context=${inputs.params.baseWorkspace}/builder-dlang
        - --cache-repo=jenkins-x-docker-registry:5000/
        - --cache=true
        - --cache-dir=/workspace
        - --skip-tls-verify-registry=jenkins-x-docker-registry:5000
        - --single-snapshot
      resources:
        limits:
          cpu: 4
          memory: 8192Mi
        requests:
          cpu: 2
          memory: 4096Mi
    - name: build-and-push-maven
      image: rawlingsj/executor:dev16
      command:
        - /kaniko/executor
      args:
        - --dockerfile=${inputs.params.baseWorkspace}/builder-maven/Dockerfile
        - --destination=${outputs.resources.maven-image.url}
        - --context=${inputs.params.baseWorkspace}/builder-maven
        - --cache-repo=jenkins-x-docker-registry:5000/
        - --cache=true
        - --cache-dir=/workspace
        - --skip-tls-verify-registry=jenkins-x-docker-registry:5000
        - --single-snapshot
      resources:
        limits:
          cpu: 4
          memory: 8192Mi
        requests:
          cpu: 2
          memory: 4096Mi
    - name: build-and-push-nodejs
      image: rawlingsj/executor:dev16
      command:
        - /kaniko/executor
      args:
        - --dockerfile=${inputs.params.baseWorkspace}/builder-nodejs/Dockerfile
        - --destination=${outputs.resources.nodejs-image.url}
        - --context=${inputs.params.baseWorkspace}/builder-nodejs
        - --cache-repo=jenkins-x-docker-registry:5000/
        - --cache=true
        - --cache-dir=/workspace
        - --skip-tls-verify-registry=jenkins-x-docker-registry:5000
        - --single-snapshot
      resources:
        limits:
          cpu: 4
          memory: 8192Mi
        requests:
          cpu: 2
          memory: 4096Mi
    - name: build-and-push-go
      image: rawlingsj/executor:dev16
      command:
        - /kaniko/executor
      args:
        - --dockerfile=${inputs.params.baseWorkspace}/builder-go/Dockerfile
        - --destination=${outputs.resources.go-image.url}
        - --context=${inputs.params.baseWorkspace}/builder-go
        - --cache-repo=jenkins-x-docker-registry:5000/
        - --cache=true
        - --cache-dir=/workspace
        - --skip-tls-verify-registry=jenkins-x-docker-registry:5000
        - --single-snapshot
      resources:
        limits:
          cpu: 4
          memory: 8192Mi
        requests:
          cpu: 2
          memory: 4096Mi
    - name: build-and-push-go-maven
      image: rawlingsj/executor:dev16
      command:
        - /kaniko/executor
      args:
        - --dockerfile=${inputs.params.baseWorkspace}/builder-go-maven/Dockerfile
        - --destination=${outputs.resources.go-maven-image.url}
        - --context=${inputs.params.baseWorkspace}/builder-go-maven
        - --cache-repo=jenkins-x-docker-registry:5000/
        - --cache=true
        - --cache-dir=/workspace
        - --skip-tls-verify-registry=jenkins-x-docker-registry:5000
        - --single-snapshot
      resources:
        limits:
          cpu: 4
          memory: 8192Mi
        requests:
          cpu: 2
          memory: 4096Mi